version: '3.8'

services:
  devops-newman:
    build:
      context:    ../db
      dockerfile: Dockerfile
    container_name: devops-newman

networks:
  default:
    external: true
    name: devops-network