version: "3.8"

services:
  devops-nginx:
    image: nginx:stable-alpine-slim
    container_name: devops-nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    external: true
    name: devops-network
