version: "3.8"

services:
  devops-api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: devops-api
    hostname: devops-api
    environment:
      - DB_HOST=devops-db
      - DB_PORT=3306
      - DB_USER=${DB__USER}
      - DB_PASSWORD=${DB__PASSWORD}
    ports:
      - 8000:8000

networks:
  default:
    external: true
    name: devops-network
