version: "3.8"

services:
  devops-newman:
    build:
      context: ../newman
      dockerfile: Dockerfile
    container_name: devops-newman
    hostname: devops-newman
    command: run /test.json --environment /env.json
    volumes:
      - ../newman/test.json:/test.json
      - ../newman/env.json:/env.json

networks:
  default:
    external: true
    name: devops-network