version: "3.8"

services:
  devops-api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: devops-api
    hostname: devops-api
    environment:
      - DB__HOST=devops-db
      - DB__PORT=3306
      - DB__USER=${DB__USER}
      - DB__PASSWORD=${DB__PASSWORD}

networks:
  default:
    external: true
    name: devops-network
