version: "3.8"

services:
  devops-newman:
    build:
      context: ../newman
      dockerfile: Dockerfile
    container_name: devops-newman
    hostname: devops-newman
    command: run /collection.json --environment /env.json
    volumes:
      - ../newman/collection.json:/collection.json
      - ../newman/env.json:/env.json

networks:
  default:
    external: true
    name: devops-network