version: '3.8'

services:
  devops-db:
    build:
      context:    ../db
      dockerfile: Dockerfile
    container_name: devops-db
    environment:
      - MYSQL_USER= ${DB__USER}
      - MYSQL_PASSWORD= ${DB__PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${DB__ROOT_PASSWORD}
      - MYSQL_DATABASE= devops

networks:
  default:
    external: true
    name: devops-network