- name: Cloner, build et up docker
  tasks:
    - name: Installer les dépendances (Docker, Git)
      ansible.builtin.apt:
        name:  "{{ item }}"
        state: latest
      loop: [ 'docker', 'docker-compose', 'git' ]

    - name: Assurer que le service Docker est démarré
      ansible.builtin.service:
        name:    docker
        state:   started
        enabled: yes

    - name: Cloner le dépôt du projet si nécessaire
      ansible.builtin.git:
        repo:   "{{ project_repo }}"
        dest:   "{{ project_path }}"
        clone:  yes
        update: yes

    - name: Construire les services avec Docker Compose
      ansible.builtin.shell:
        cmd:   docker-compose build
        chdir: "{{ project_path }}"

    - name: Démarrer les services avec Docker Compose
      ansible.builtin.shell:
        cmd:   docker-compose up -d
        chdir: "{{ project_path }}"