- import_playbook: "{{playbook_dir}}/configure.yml"

- name: Build and deploy the application using Docker Compose
  hosts: localhost
  tasks:
    - name: Ensure Python pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install specific version of Docker SDK for Python
      ansible.builtin.pip:
        name: docker==6.1.3
        state: present

    - name: Check if Docker Desktop is running
      ansible.builtin.command: pgrep -f docker
      register: docker_check
      failed_when: docker_check.rc != 0

    - name: Start Docker Desktop if it is not running
      ansible.builtin.command: open -a Docker
      when: docker_check.rc != 0

    - name: Créer le réseau Docker pour l'application DevOps
      docker_network:
        name: devops-network
        state: present
        driver: bridge

    - name: Build and start the Docker Compose application
      docker_compose:
        project_src: "{{playbook_dir}}/../"
        build: yes
        state: present

    # Ajout de la logique d'attente pour le conteneur devops-newman
    - name: Waiting for the devops-newman container to terminate
      community.docker.docker_container_info:
        name: devops-newman
      register: newman_info
      until: newman_info.container.State.Status == "exited"
      retries: 60
      delay: 10
      ignore_errors: true

    - name: Check whether the devops-newman container has been successfully exited
      fail:
        msg: "The devops-newman container did not terminate correctly with exit code {{ newman_info.container.State.ExitCode }}"
      when: newman_info.exists and newman_info.container.State.ExitCode != 0
