- import_playbook: "{{playbook_dir}}/configure.yml"

- name: Build and deploy the application using Docker Compose
  hosts: localhost
  tasks:
    - name: Ensure Python pip is installed
      ansible.builtin.package:
        name:  python3-pip
        state: present

    - name: Install specific version of Docker SDK for Python
      ansible.builtin.pip:
        name:  docker==6.1.3
        state: present

    - name: Check if Docker Desktop is running
      ansible.builtin.command: pgrep -f docker
      register: docker_check
      failed_when: docker_check.rc != 0

    - name: Start Docker Desktop if it is not running
      ansible.builtin.command: open -a Docker
      when: docker_check.rc != 0

    - name: Créer le réseau Docker pour l'application DevOps
      docker_network:
        name: devops-network
        state: present
        driver: bridge

    - name: Build and start the Docker Compose application
      docker_compose:
        project_src: "{{playbook_dir}}/../"
        build: yes
        state: present